### ISSUE TITLE
volume group can change

### ISSUE THREAD

**Issue by runcom** [containers/docker-lvm-plugin#7] opened 2016-05-03 14:07 UTC
Right now we resolve the VOLUME_GROUP in each call (create, remove, etc, etc). This isn't quite right to me. Because we can create a logical volume in a volume group - then change the volume group in the config file - and fail to remove for instance a logical volume (case the vg name changed at runtime!!!!).
I think it would be great if the VOLUME_GROUP is first resolved at plugin init time and saved in memory for that plugin life while allowing ppl via an --opt to choose the volume group to use

@rhvgoyal @rhatdan @shishir-a412ed wdyt (I'm not sure it could work, just thinking out loud)

**Comment by shishir-a412ed** [comment] 2016-05-12 16:09
Let me understand what you are trying to say, feel free to correct me :)

What is happening as of today:

I have a volume group (volume_group_one). I update the name of the volume group in the config file `/etc/docker/docker-lvm-plugin` and I create a logical volume using the plugin.
```
$ docker volume create -d lvm --name foobar --opt size=0.25G
```
A user goes and does `vgrename volume_group_one volume_group_two`. Now when I run `lvs` I would see `foobar` listed under volume_group_two, however the config file is not updated.

So when I try to create another logical volume:
$ docker volume create -d lvm --name foobar-new --opt size=0.25G.

This will throw this error: https://github.com/projectatomic/docker-lvm-plugin/blob/master/driver.go#L60
This to me is expected behavior.
`Error creating volume`. Error message to me however is NOT CORRECT.
This should give more information to user, why there was an error creating the volume and volume group name is not correct. So that user can go and update the config file with correct volume group name (volume_group_two).

What you are suggesting:

Save the volume group name in memory at plugin init time. and allow users to pass an --opt to choose volume group name.

Questions:

a) If I actually change my volume group name FROM volume_group_one TO volume_group_two, Since the memory would have an old value, how do I provide a refresh. Does user has to do docker-lvm-plugin daemon restart ? Does he pass the new volume group name via --opt ?
b) If the user pass a volume group name via --opt, and we save the name in memory. and there is an unexpected docker-lvm-plugin daemon restart. How is the value preserved ?

Shishir

**Comment by mortya** [comment] 2018-10-07 04:02
I think the original poster's case is like so:

1. docker-lvm-plugin is initially configured to use one system VG.  Say, "vg1".
2. user creates a few volumes.  Say, foo and bar.  foo and bar are using vg1.
3. the admin comes along, creates vg2, configures docker-lvm-plugin to use vg1, and restarts it.
4. foo and bar still exist.  But some docker commands that reference them will fail, because docker-lvm-plugin expects the volumes to be in vg2, not vg1.

I played around, and reproduced this.  docker-lvm-plugin works with only one VOLUME_GROUP at a time.

The problem could be fixed by having docker-lvm-plugin somehow associate the value of VOLUME_GROUP with each volume at the time of its creation.

The obvious workaround is to delete all docker lvm volumes before changing VOLUME_GROUP.  :)

Personally, I don't care about this issue, because I would not mess with volume groups on a production host, anyway.  :)

**Closed** 2019-11-22 21:07 UTC
Labels: enhancement
